Update ShortHand_Practice.py
line 46, modified the max_value from 20 to 0, cause:
StreamlitAPIException: The default value 20 must be less than or equal to the max_value 0